        EXTRN PLAYER1OBJECTS:WORD
        EXTRN PLAYER2OBJECTS:WORD
        EXTRN BLOCKP1:WORD
        EXTRN COINP1:WORD 
        EXTRN BLOCKP2:WORD
        EXTRN COINP2:WORD
        EXTRN BLOCK_SPEED:BYTE 
        EXTRN COIN_SPEED:BYTE
        PUBLIC ADD_NEW_OBJECTS    

CREATE_SET_OBJECT_POSITION MACRO OBJ,SPEED
    PUSH AX
    PUSH BX
    PUSH CX
    PUSH DX 
	;NUMBER OF ROWS PER PLAYER
    MOV BX,07H
	MOV AX,0H
    MOV OBJ,AX
    ;GET THE SYSTEM TIME
    MOV AH,0
    INT 1AH
    ;GET RANDOM ROW POSITION
    MOV AX,DX
    MOV DX,0H
    DIV BX      
    ;ROW POSITION SHIFTED TO THE WRIGHT POSITION IN THE BYTE
    SHL DX,1
	SHL DX,1
	SHL DX,1
	SHL DX,1
	SHL DX,1
	MOV CX,0
    OR CX,DX 
    ;COL POSITION AT COL 79
	OR CX,4F00H 
    ;SPEED
    MOV DL,SPEED 
    MOV DH,0
    SHL DX,1
	SHL DX,1
    OR CX,DX
    ;VALIDATION BIT
    OR CX,01
    MOV OBJ,CX 
	POP DX
	POP CX
    POP BX
	POP AX           
ENDM     
		
ADD_TO_ARRAY MACRO ARRAY,OBJ 
    LOCAL TRAVERSE,FINISH,CONTINUE
    MOV SI,0  
TRAVERSE:
    MOV AX,ARRAY[SI]
    CMP AX,0FFFFH
    JE FINISH  ;IF THAT HAPPEND WITHOUT ADDING THEN THERE IS A PROBLEM
    MOV BX,1
    AND BX,AX
    JNZ CONTINUE
    MOV BX,OBJ
    MOV ARRAY[SI],BX
    JMP FINISH
CONTINUE: 
    INC SI
    INC SI
    JMP TRAVERSE
FINISH:    
ENDM    
		

.MODEL SMALL
.STACK 64
.DATA
.CODE
ADD_NEW_OBJECTS PROC FAR
	 
    CALL CREATE_OBJECTS
	ADD_TO_ARRAY PLAYER1OBJECTS,BLOCKP1
    ADD_TO_ARRAY PLAYER1OBJECTS,COINP1
    ADD_TO_ARRAY PLAYER2OBJECTS,BLOCKP2
    ADD_TO_ARRAY PLAYER2OBJECTS,COINP2    
	RET
ADD_NEW_OBJECTS ENDP 

CREATE_OBJECTS PROC NEAR
		CREATE_SET_OBJECT_POSITION BLOCKP1,BLOCK_SPEED
		MOV CX,BLOCKP1
	;TYPE
		OR CX,2H  
		MOV BLOCKP1,CX  
    ;TO GET D7,D6,D5
		MOV BX,00E0H
		AND BX,CX
REGENERATE: 
		CREATE_SET_OBJECT_POSITION COINP1,COIN_SPEED
		MOV CX,COINP1
    ;TYPE
		OR CX,0H
    ;CHECK IF COIN LOCATION = BLOCK LOCATION 
		MOV DX,CX
		AND DX,00E0H
		CMP DX,BX
		JE REGENERATE
		MOV COINP1,CX  
		RET
CREATE_OBJECTS ENDP   


    

END    

