;TEAM 5
;THIS IS THE PROJECT MAIN LOOP
;===========================================
INCLUDE Util.asm

EXTRN SERIAL_INITIALIZE:FAR
EXTRN SERIAL_SEND_FROM_BL:FAR
EXTRN SERIAL_RECIEVE_TO_BH:FAR
EXTRN SERIAL_RECIEVE_TO_BH_WAITS:FAR
EXTRN MAIN:FAR
;EXTRN CHAT
PUBLIC P1USER_NAME 
PUBLIC P2USER_NAME 

.MODEL SMALL
.STACK 64
.DATA
	P1USER_NAME DB 15 DUP('$')
	P2USER_NAME DB 15 DUP('$')
	USERNAME DB 14,?,15 DUP('$')

	STR1 DB 'PRESS F1 TO START CHATTING','$'
	STR2 DB 'PRESS F2 TO START GAME','$'
	STR3 DB 'PRESS ESCAPE TO END THE PROGEAM','$'
	STR4 DB 'WAITING FOR PLAYER 2 USER NAME','$'
	MES DB 'PLEASE ENTER YOUR USERNAME$'

.CODE
PROGRAM_MAIN PROC FAR 
	MOV AX,@DATA
	MOV DS,AX

	CALL FIRST_PAGE
	SET_CURSOR 10,30
	WRITE_STRING STR4

	
GAME_LOOP:
	CALL MAIN_PAGE

	MOV AH,0H
	MOV AL,03H
	INT 10H
	
	JMP GAME_LOOP

	RET	
PROGRAM_MAIN ENDP

MAIN_PAGE PROC NEAR
	
	SET_CURSOR 10,30
	WRITE_STRING STR1
	SET_CURSOR 11,30
	WRITE_STRING STR2
	SET_CURSOR 12,30
	WRITE_STRING STR3
GET_ANOTHER_KEY:
	MOV AH,0
	INT 16H
	CMP AH,3BH
	JNE NEXT
	;CALL CHAT
	JMP END_MAIN_PAGE
NEXT:
	CMP AH,3CH
	JNE NEXT1
	CALL MAIN
	JMP END_MAIN_PAGE
NEXT1:
	CMP AH,1
	JNE GET_ANOTHER_KEY
	MOV AH,4CH
	INT 21H
END_MAIN_PAGE:
	RET
MAIN_PAGE ENDP

FIRST_PAGE PROC NEAR
	MOV AH,0H
	MOV AL,03H
	INT 10H

        MOV AH,2
        MOV DX,091BH
        INT 10H     
        
        MOV AH, 9
        MOV DX, OFFSET MES ;Display string in the new location
        INT 21H 
        
        MOV AH,2
        MOV DX,0B1BH
        INT 10H  
                    
        mov ah,0AH        ;Read USERNAME from keyboard
        mov dx,offset USERNAME                  
        int 21h  
         
	MOV AH,0H
	MOV AL,03H
	INT 10H
	RET
FIRST_PAGE ENDP
END
